* 关于做活 2 币商城的几个方案
** 渠道
*** 商家合作（线下）
**** 赛纳维
对于赛纳维，可以是我们做商家合作的第一个试点，其中有对内对外两个方面。
***** 对内
对内是说对我们内部员工（也就是说慢连和捕风一般员工）
对内我们可以限制每月的消费金额（如 300），然后超出金额可以用 2 币支付（慢连员工可做适当 2 币补贴）
也可以都使用 2 币支付，免去了纸上记录谁一顿吃了多少钱。
***** 对外
对外是说赛纳维对其他来店消费的客户使用第 2 空间 2 币支付
这是我们的一个试点，我们按对待其他商家一样的正规方式做，看用户的反馈来指导我们是否要推广。
**** 太平洋咖啡
太平洋咖啡分布广，有股东这方面的资源，可太平洋咖啡合作可验证我们是否有与大型连锁机构合作的能力。
也能进一步推动用户运营。
**** 周边商家
周边商家合作是在验证了商家支付模式成功的前提下进行。
**** 本地商家
本地商家由运营或市场人员联系。
**** 其他商家
最后可做网上签约认证，对于大型连锁机构我们可谈相应合作。
*** 购买商品（电子商务）
**** 我们自己的产品
光东东系列，各种红酒，第 2 空间虚拟产品
**** 照片冲洗
超片冲洗，做相册等服务，最好是接第三方
**** 秒杀活动等
可筛选一些新奇的东西来卖，组织抢购秒杀等活动来活跃人气
*** 兑换流量
用户使用第 2 空间需要耗费流量，2 币可以兑换流量
*** 话费充值
方便用户给手机充值话费
*** 礼品卡
京东等电商平台电子卡
*** 生活缴费（不推荐）
水费电费网费等，不推荐是因为这里会有纠纷
*** 景点门票（不推荐）
各类景点门票，可做内容推广，我们写一篇文章介绍某个地方，然后末尾可以用 2 币购买这个景点的门票，不推荐是因为这个做起来页面复杂，功能多，工作量巨大
*** 酒店机票（不推荐）
同上面景点门票一般，不推荐。
** 商家合作支付方式
*** 商家对接
在塞纳维餐厅试点，论证模式可行，然后运营（市场）人员在周边、本地推广商家，可和太平洋咖啡等大型连锁机构谈合作。

商家需注册第 2 空间帐号，认证为商家，绑定其商家运营者（可多个）微信帐号（获取通知），老板微信帐号（用来收钱），
我方负责每个商家二维码的物料。
*** 扫码支付
用户来商家消费，打开手机微信使用扫一扫功能扫描我方二维码，输入消费金额点击支付。
已注册第 2 空间用户可以使用 2 币支付，未注册或 2 币不够的情况下，可使用微信支付（可做只补 2 币不够的差价）。

用户体验可以做到和使用微信支付一样。
*** 商家收入
理想状态用户付款后，商家只增加 2 币，可提现到微信零钱。
由于我们有提现手续费，前期推广我们可以用户付款后，商家直接收到微信零钱，以便我们推广。

其中微信会问我们收取 2%手续费，这些我们得做补贴。
** 分析结论
做活 2 币商城，不仅仅是一个强运营工作，而且有不少的开发量，做成之后，还要给用户端适当的补助，微信支付手续费相应补助等。
不可一蹴而就，线上工作可以先展开，线下得运营推动，西安不比一线城市，还是先做餐厅，先让内部员工用起来，再看市场反馈。
