* 我们需要谈的条件
** 提供标准的数据交换格式（转码）
提供杂志 PDF 文件（或每页图片）
所有文章的标准数据交换格式（XML 或 json），其中至少包含标题/作者等信息（插图最好也要有）
** 往期杂志数据
提供往期 30+年杂志数据
** 往期杂志定价
往期（一年以前）杂志可以免费阅读
或可低价阅读
** 平台定价不能和高于其他电商平台
如在亚马逊平台下 2.99 元一期，在我们这边不能超出此价格（可谈）
允许平台内部做相应促销活动
** 杂志必须连续，不能中间缺少
上传每期杂志，最迟不能超过本期杂志发布时间
** 定价不能随意更改
读者杂志享有平台自主定价权，但是不能随意变动（会涉及已订阅用户利益）
需双方商定后方可修改定价
** 保证购买用户拥有文章分享版权
用户购买某期读者杂志，看某一篇文章觉得不错可以分享到朋友圈获取朋友打赏
** 提供整合开发调试时间
合作日期生效前，需提供开发调试时间
期间只需要一期杂志数据
* 读者合作协议中所能提供的资源
** 读者品牌
** 杂志数据
** 2 例杂志广告
*** 报价
| 版位      | 收费 |
|-----------+------|
| 封二/前插 | 30W  |
| 中插      | 30W  |
| 后插      | 25W  |
| 封三      | 28W  |
| 封底      | 36W  |
** 10 例微信广告
*** 报价
| 广告位 | 广告刊例 |
|--------+----------|
| 单图   | 5W       |
| 多图一 | 3.6W     |
| 多图二 | 3W       |
| 多图三 | 2.6W     |
| 多图末 | 2.4W     |
* 读者和其他互联网相关产品合作分析
** 酷讯
2007 年
《读者》欲再造互联网品牌 携手酷讯做生活搜索
成立于 06 年 3 月份的生活搜索酷讯在一年多的时间里，已经获得了 1200 万美金的风险投资并成长为中国最大的火车票搜索、中国最大的房产搜索、中国最大的旅游搜索引擎。目前每日超过 300 万的用户使用酷讯，酷讯也成长为中国生活搜索的第一品牌。
“酷讯生活搜索的本地化优势，非常适合《读者》从一棵树到一片林的发展宗旨，这次合作不仅仅是品牌的传播，更是一次文化的传播。”

原生活搜索方向，现美团旗下酷讯旅游
** 半壁江原创文学网
2010 年
半壁江原创文学网与《读者》结成战略合作关系
半壁江原创文学网早在 2009 年初成立之时，就与《读者》(乡土人文版)结成了合作关系，半壁江原创文学网利用自己的网络平台，展示《读者》(乡土人文版)过刊作品、刊联信息、最新期刊动态，并向乡土人文版提供大量原创作品推荐。

网站流量平均 0.5k
** 智能手机
2012 年
《读者》智能手机上市 传统期刊“探路”数字阅读
《读者》杂志日前与ＰＨＩＣＯＭＭ斐讯合作在上海推出首款读者智能手机，成为数字化大潮下中国传统期刊“探路”数字阅读、文化出版机构与通讯设备解决方案提供商跨界定制智能手机的先例。
其一大“卖点”在于独家内置了“读者杂志三十年珍藏合刊”内容，同时还支持《读者》最新的“云图书馆”的海量电子图书阅读下载。通过《读者》云图书馆，用户可以自行进行新期刊的下载。
** 龙源版权
2012 年
《读者》与龙源版权合作推广数字阅读
《读者》将通过龙源数字发行平台向国内外的个人用户和机构用户提供全文电子版数字阅读和推广营销服务。
** 读者云图书馆
官网首页链接读者集团，读者数码
有 APP 下载
* 读者价值分析
** 品牌价值
品牌的新闻价值
** 数据价值
30+年数据，有一定的受众
做好 SEO 工作，能给平台带来部分流量
** 公众号文章阅读量
每篇首位几乎都在 10+
预计能产生 1W 粉丝
** 杂志广告价值
*** 产品宣传
*** 粉丝转化率
纸质媒体对于互联网产品转化率低
以 600W 粉丝算，预计能产生 3K 粉丝
** 吸引内容产生者（读者投稿者、作家）
和读者杂志合作，广告标语上可以写我们产品的特点（比如说收费阅读）
因为读者杂志的受众人群不只是“读者”还有作者，作者看到读者杂志的广告可能会尝试我们产品，最终成为我们的用户
* 关于谈价钱的最后结论
** 50W
广告按 50%计算：
杂志广告 30W * 2 + 微信广告 3W * 10 = 90W * 50% = 45W
按 40%计算则是：90W * 40% = 36W

带回的收益包括：

1.品牌的新闻价值
2.数据价值
3.公众号引流
4.杂志引流

品牌和数据价值不好估计，鉴于读者做过不少电子化阅读，互联网方向，所以降低品牌和数据的价值估计，最后预计能带来 5k 粉丝

公众号引流 1W + 杂志引流 3K = 1.3W 粉丝

粉丝价格按 10 元算是 13W
我们带来的利益是 18W
** 20%
最终我们操作，基本只能走按年、半年去订阅
付费订阅用户估计一年能达到 1k，一期以 2 元计算
1K * 2 * 48（一年）= 10W * 20% = 2W
** 结论
- 不推荐和读者的这次合作
- 价钱能谈到 20W 和 20%，可达到估计的广告价值，当广告打，可谈
- 价钱高于 35W（广告费 40%），拒绝
- 合作前提肯定是我们能自动化处理他们的杂志数据，否则拒绝
- 基于读者做过多个互联网相关数字阅读方向，最后都没做大，反思我们是否要走数字阅读这条路，我们要做，需要有哪些特点才能不走以前一些产品的路
