* 市场文化的规律-读《下一个倒下的会不会是华为》

透视社会依次有三个层面：技术、制度和文化。华为早期是没有技术可言的，有的只是军事化
的管理制度和遵循规律的强势文化。

华为的成功不是偶然，是遵循了市场文化规律，在信息时代的背景下，坚持了下来，所以成功了。

** 常识
书中反复强调华为价值观，有趣的是目录中写着“常识、真理”，书中这样写：

#+BEGIN_SRC 
常识即真理，世界上但凡成功的企业莫不是客户导向的，客户是企业存在和发展的唯一理由，
这种观点并非任正非所发明的，本来就是千年以来商业社会的基本法则，甚至可以称之为基本
的人类商业伦理，但在资本化、技术化的时代却被模糊了，乃至于抛弃了，股东乃上帝、技术自
己狂的潮流将常识和真理淹没了。
#+END_SRC

常识这个词可能用得不是很好，因为常识有时候可能并不是真理。

华为的价值观其实就是很普通很简单的市场文化规律。

** 人
华为重视人，“工者有其股”只是其中一项激励手段，让员工成为公司的主人，当然谁都知道
普通员工还是不可能成为公司的主人，只是利益挂钩，最终还是市场手段来控制人。

不管是大公司还是小公司，人都是最重要的，这也是规律，是真理。

** 加班
所谓的艰苦奋斗。

我不是很喜欢艰苦奋斗这个词，感觉一下回到了毛泽东那个年代。

华为的加班文化一直贯彻上下，离职出来创业的也一直遵循加班文化。

之所以把加班称之为文化，是因为这里的加班是长期的加班，是一直再加班。这是一种企业文化。

** 低成本
华为制胜的法宝。

低成本，成本又低在哪里？

人力成本上华为给高工资，但是高工作量，人力成本低。

时代背景，整个产业链成本低。

** 灰度
灰度理论讲的是，在黑白之间要有灰度。在是非之间，要有宽容和妥协。

这是华为在成为“大公司”以后才有的理论。

灰度就是不玩零和游戏，达到双赢的目的。

在开发上有灰度发布、灰度测试等。

** 革命
自我批判与变革是每个企业必须不断直面的生存之道。

居安思危。

** 活下去
活下去才是华为能成功的道理。

** 关于书
论证了华为为什么会成功，华为只要坚持这些规律就不会倒下。

《华为》和《海底捞》作为中国企业管理、员工教育的典范，过分推崇。

本书作为一本了解华为，了解任正非的参考书、工具书还行，过分的吹捧华为，夸赞任正非的英明，
作为书籍来说，收获性不强。

** 收获
成功没有什么捷径，需要实实在在的付出时间和心血来铸就。即使这样，还需要有大的时代背景
和好的方向（条件），否则还是逆势而为。
